### ISSUE TITLE
NLU for example node client responds "didnt get that"

### ISSUE THREAD

**Issue by RisteardMacF** [soundhound/hound-sdk-web-example#8]
Hi,

When I run the node client example using the example test_audio files, the nlu response is a NoResultCommand.  I can see transcription working however.  Full output logged is below.

Any help appreciated.

**Console Output**
Partial Transcript:
Partial Transcript:
Partial Transcript:
Partial Transcript:
Partial Transcript:
Partial Transcript: what
Partial Transcript: what is
Partial Transcript: what is
Partial Transcript: what is the
Partial Transcript: what is the whe
Partial Transcript: what is the weather
Partial Transcript: what is the weather
Partial Transcript: what is the weather
Partial Transcript: what is the weather there
Partial Transcript: what is the weather there
Partial Transcript: what is the weather there
Partial Transcript: what is the weather there
Partial Transcript:
Partial Transcript: what is the weather there
Response {
  Format: 'SoundHoundVoiceSearchResult',
  FormatVersion: '1.0',
  Status: 'OK',
  NumToReturn: 1,
  AllResults:
   [ { CommandKind: 'NoResultCommand',
       SpokenResponse: '',
       SpokenResponseLong: 'Didn\'t get that!',
       WrittenResponse: 'Didn\'t get that!',
       WrittenResponseLong: 'Didn\'t get that!',
       AutoListen: false,
       ViewType: [Array],
       TranscriptionSearchURL: 'http://www.google.com/#q=what%20is%20the%20weather%20there' } ],
  Disambiguation: { NumToShow: 1, ChoiceData: [ [Object] ] },
  ResultsAreFinal: [ true ],
  DomainUsage: [],
  BuildInfo:
   { User: 'jenkinslave',
     Date: 'Wed Mar 17 18:06:04 PDT 2021',
     Machine: 'f28kbm2.pnp.melodis.com',
     GitCommit: '361b850efb2df6cebf8a691841dff73c6b7d5190',
     GitBranch: 'origin/master',
     BuildNumber: '6955',
     Kind: 'Low Fat',
     Variant: 'release' },
  QueryID: 'ece88bad-f728-3243-0294-2f2b721ddf64',
  ServerGeneratedId: 'ece88bad-f728-3243-0294-2f2b721ddf64',
  AudioLength: BigNumber { s: 1, e: 0, c: [ 1, 73000000000000 ] },
  RealSpeechTime: BigNumber { s: 1, e: 0, c: [ 1, 41833100000000 ] },
  RealTime: BigNumber { s: 1, e: 0, c: [ 1, 60078100000000 ] } }

**Comment by nsharifli** [comment]
Hi @RisteardMacF ,
I have updated the sample audio with “How is the weather like in Toronto?”. It should also work with queries such as “How is the weather?”  or “How is the weather here”. The existing audio was not a good example and now is removed. Because of the ambiguity of the query the backend responded with NoResultCommand.

Thank you for bringing this up.

**Comment by RisteardMacF** [comment]
Fantastic, thank you very much

**Comment by nsharifli** [comment]
You are welcome!
